Reduce layout size by using reference in Action::HoldTap variant
TeXitoi/keyberon pull request #95
Opened 2022-07-23 19:38 UTC by jedrzejboczar

Hi, I noticed that recent commits made the size of Action::HoldTap variant grow in size (tap_hold_interval, HoldTapConfig::Custom). As of [57aa0d3](https://github.com/TeXitoi/keyberon/commit/57aa0d306b60432e2eede2e33ae9a0cacfb70166) the Action type takes 24 bytes (on 32-bit systems). This is due to the size of the `Action::HoldTap` variant (as enums are union types, so the size is determinant + max size of variants), as can be seen here:
![action_now](https://user-images.githubusercontent.com/16623787/180618135-f569c302-7224-4f5e-a72a-8a23ade79071.png)

When combined with the fact that there are `ncols*nrows*nlayers` actions, this can take a considerable amount of space in chip memory. E.g. in my keyboard with `ncols=12, nrows=5, nlayers=5` this results in 7200 bytes.

> Side note: the full size of a layout is the above + `N*1B` for each MultipleKeyCodes + `N*24B` for each MultipleActions + `2*24B` for each HoldTap (2 refs to Action). This might be a bit less if some of the references point to the same object.

In most scenarios users don't use HoldTap too often, so having it embedded in the Action struct is unnecessary. This PR creates a new `HoldTapAction` struct, and uses a reference in the HoldTap variant:
```rust
pub enum Action<T = core::convert::Infallible>
{
    // ...
    HoldTap(&'static HoldTapAction<T>),
    // ...
}
pub struct HoldTapAction<T>
{
    // ...
}
```

This way the HoldTap variant  takes only 4 bytes, reducing the overall size of Action to 12 bytes, which allows to reduce the size of layout by up to 50% (when no HoldTap variants are used). In case of my layout with 5 layers and 9 HoldTaps I was able to go down from 7200 B to 3960 B (reduction by 47.5%). 

This is how the sizes look when using a reference:
![action_after](https://user-images.githubusercontent.com/16623787/180618757-2be0c83f-c314-4fc1-9a5d-45be0a8da818.png)
![hold_tap_after](https://user-images.githubusercontent.com/16623787/180618761-dd981365-5658-46f7-84fb-6158d7a0b3a6.png)

2022-07-23 19:53 UTC, jedrzejboczar commented
I also wonder if it would be possible to go down even more by decreasing the size of MultipleKeyCodes and MultipleActions. Currently these are slices which are implemented as "fat pointers" in Rust, which means that `&'static [KeyCode]` stores a start address and a length (4B + 4B on 32-bit system). However it should be possible to reduce it to just an address and move the size to the location of the array. This would make Action tak only 8 bytes in total (so 66% reduction from current 24 bytes). 

Easiest way would be to just have double indirection, so something like `MultipleKeyCodes(&'static &'static [KeyCode])`. But maybe it's possible to have something like:
```rust
pub enum Action<T = core::convert::Infallible>
{
    MultipleKeyCodes(&'static Slice<KeyCode>),
}
struct Slice<T, const N: usize> {
    length: usize,
    data: [T; N],
}
```
but I am not sure how to get rid of of the generic `N` parameter.

Of course double indirection hits the performance (more load instructions) but I feel like accessing actions isn't a critical point in terms of performance.

2022-07-23 20:02 UTC, jtroo commented
Idea: add a test to track regressions in the enum size. E.g. eg using `[sizeof](https://doc.rust-lang.org/core/mem/fn.size_of.html)`

2022-07-25 09:02 UTC, jedrzejboczar commented
I added the test for Action size.

And here is a quick proof of concept of using thin slices: https://gist.github.com/jedrzejboczar/9272e1a838f04e37214a58e9d52744d0. With this approach adding MultipleKeyCodes/MultipleActions becomes a bit more verbose due to the `ThinSlice::new` call, but `layout!` or some other macro could hide the added complexity.

2022-08-01 14:25 UTC, jedrzejboczar commented
I changed `MultipleKeyCodes` and `MultipleActions` to references-to-slices as noted earlier:

> Easiest way would be to just have double indirection, so something like `MultipleKeyCodes(&'static &'static [KeyCode])`.

So now with this PR the size of  `Layers` should be close to 66% less (depending on how many `HoldTap`/`Multiple...` variants are used in the layout. For me this is an overall reduction from 7544 B to 2884 B. 

---

And the gist I linked [in previous comment](https://github.com/TeXitoi/keyberon/pull/95#issuecomment-1193778960) is incorrect, my mistake when doing a quick poc. It is equivalent to `&'static &'static [KeyCode]` so there is no sense in implementing such a custom type. 

A different variant should look like what I shown [in the comment before](https://github.com/TeXitoi/keyberon/pull/95#issuecomment-1193180015), where the array is embedded in the struct (so there is only one "level" of pointers), but as noted I don't know how to get rid of the const generic parameter. Anyway I think it's not worth optimizing further (it probably wouldn't give any noticeable performance gains).

2022-08-01 14:26 UTC, TeXitoi requested changes
Thanks. The improvement is real. I hope the little ergonomic lose will not be too visible.

2022-08-01 14:41 UTC, jedrzejboczar commented on src/action.rs
> +    pub tap: &'static Action<T>,
Right

2022-08-01 15:14 UTC, merged